export default {
    container: {
        backgroundColor: "#095D6A",
        height: "100%",
      },
      image: {
        alignSelf: "center",
        marginTop: "5%",
        resizeMode: "contain",
        width: 120,
        height: 120,
      },
      iconContainer: { marginHorizontal: "5%" },
      input: {
        paddingVertical: 15,
        paddingHorizontal: 18,
        backgroundColor: "rgba(253, 246, 240, 0.6)",
        marginHorizontal: "10%",
        borderRadius: 4,
        fontSize: 14,
        fontFamily: "Rubik-Regular",
        marginTop: 25,
        color: "#FDF6F0",
      },
      buttonContainer: {
        marginTop: 40,
        flexDirection: "row",
        justifyContent: "center",
        marginHorizontal: "10%",
        paddingVertical: 20,
        backgroundColor: "#FBBC58",
        borderRadius: 4,
      },
      buttonText: {
        alignSelf: "center",
        fontFamily: "Rubik-Regular",
        color: "#FDF6F0",
        fontSize: 14,
      },
      dropdown: {
        paddingVertical: 5,
        paddingHorizontal: 18,
        backgroundColor: "rgba(253, 246, 240, 0.6)",
        marginHorizontal: "10%",
        borderRadius: 4,
        fontSize: 14,
        marginTop: 25,
        color: "#FDF6F0",
      },
      placeholderStyle: {
        fontSize: 14,
        fontFamily: "Rubik-Regular",
        color: "rgba(9, 93, 106, .6)",
      },
      selectedTextStyle: {
        fontSize: 14,
        fontFamily: "Rubik-Regular",
        color: "#FDF6F0",
      },
}