import global from "../../global";

export default{
    borderColorDay:"white",
    placeHolderTextColor: global.color.primaryColors.placeHolderTextColor,
    iconColor: global.color.primaryColors.iconColor,
    cancelColor: global.color.primaryColors.text,
    container:{
        backgroundColor: global.color.primaryColors.background,
        height: "100%",
      },
    socialRow: {
      flexDirection: "row",
      justifyContent: "space-around",
      marginHorizontal: "5%",
      marginBottom: "8%",
    },
    image: {
      alignSelf: "center",
      marginTop: "5%",
      resizeMode: "contain",
      height: 120,
      width: 120,
    },
    imageContainer: {
      borderRadius: 100,
      borderWidth: 2,
      width: 150,
      height: 150,
      alignSelf: "center",
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
      backgroundColor: global.color.primaryColors.adjacent,
      borderColor: global.color.primaryColors.adjacent,
      marginTop: "5%",
    },
    dayContainer: {
      width: "29%",
      borderColor: global.color.primaryColors.main,
      alignItems: "center",
      padding: "5%",
      borderWidth: 1,
      borderColor: global.color.primaryColors.adjacent,
      borderRadius: 12,
      backgroundColor: global.color.primaryColors.adjacent,
    },
    dayRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginHorizontal: "10%",
      borderColor: "white",
    },
    timeText: {
      fontFamily: "Rubik-Regular",
      color: global.color.primaryColors.main,
      fontSize: 16,
    },
    timeContainer: {
      width: "47%",
      borderColor: global.color.primaryColors.main,
      alignItems: "center",
      padding: "5%",
      borderRadius: 12,
      backgroundColor: global.color.primaryColors.adjacent,
      borderWidth: 1,
      borderColor: global.color.primaryColors.adjacent,
    },
    timeRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginHorizontal: "10%",
      borderColor: "white",
    },
    headerText: {
      fontFamily: "Rubik-Regular",
      fontSize: 18,
      color: global.color.primaryColors.text,
    },
    headerContainer: {
      margin: "8%",
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    input: {
      paddingVertical: "5%",
      marginHorizontal: "5%",
      fontSize: 16,
      fontFamily: "Rubik-Regular",
      color: global.color.primaryColors.text,
    },
    inputContainerSocial: {
      backgroundColor: global.color.primaryColors.adjacent,
      alignSelf: "center",
      justifyContent: "center",
      alignItems: "center",
      width: 90,
      height: 90,
      borderRadius: 100,
    },
    inputSocial: {
      fontSize: 16,
      fontFamily: "Rubik-Regular",
      padding: "5%",
      marginTop: 5,
      width: "85%",
      borderRadius: 12,
      marginHorizontal: "8%",
      backgroundColor: global.color.primaryColors.adjacent,
      color: global.color.primaryColors.text,
    },
    inputContainer: {
      borderRadius: 12,
      marginHorizontal: "8%",
      marginTop: "5%",
      backgroundColor: global.color.primaryColors.adjacent,
    },
    inputHeader: {
      color: "#757575",
      fontFamily: "Rubik-Regular",
    },
  }